volumes:
  prom:
  tempo:

services:
  client:
    image: ghcr.io/go-faster/simon:0.9.3
    restart: always
    command:
      - "client"
      - --upload-rps=1
      - --upload-hash-iterations=1
    environment:
      - SERVER_ADDR=http://server:8080
      - OTEL_ZAP_TEE=0
      - OTEL_LOG_LEVEL=debug
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
  server:
    image: ghcr.io/go-faster/simon:0.9.3
    restart: always
    command: ["server"]
    environment:
      - HTTP_ADDR=0.0.0.0:8080
      - OTEL_ZAP_TEE=0
      - OTEL_LOG_LEVEL=debug
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317

  # https://opentelemetry.io/docs/collector/installation/#docker-compose
  otelcol:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.89.0
    volumes:
      - ./otelcol.yml:/etc/otelcol-contrib/config.yaml
    environment:
      # probably excessive
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otelcol:4317
    command:
      - "--config"
      - "/etc/otelcol-contrib/config.yaml"

  tempo-init:
    # Need to chown first
    # https://github.com/grafana/tempo/issues/3601
    image: ubuntu
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo:/var/tempo
  tempo:
    image: "grafana/tempo"
    command: ["-config.file=/etc/tempo.yml"]
    depends_on:
      - tempo-init
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - tempo:/tmp/tempo

  grafana:
    image: "grafana/grafana:11.5.0"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor,traceToMetrics,publicDashboards,tempoApmTable
      - GF_ALERTING_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=debug
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./grafana/dashboards:/etc/grafana/dashboards:ro

